Команда AviaJ, РК№2
java-park-mail-ru/aviaj-09-2016 pull request #2
Opened 2016-11-15 20:25 UTC by TimeEscaper

2016-11-15 21:38 UTC, KSolovyev requested changes

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/controller/AuthenticationController.java
> +    public static final class UserRequest {
давайте эти классы в конец

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/controller/RegistrationController.java
> +        catch (ConnectException e) {
оберните в try catch только то, что реально может выбросить исключение. А то так не понятно, где опасный код

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/controller/RegistrationController.java
> +        catch (ConnectException e) {
это надо сделать везде, не только в этом месте

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/dao/UserProfileDAO.java
> +            System.out.println(Integer.toString(e.getErrorCode()) + ": " + e.getSQLState());
Вместо вывода в стандартный поток вывода, надо использовать логгер
`private static final Logger LOGGER = LoggerFactory.getLogger(Some.class)`
`LOGGER.error("Error getting a user (login = )" + login, e);`

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +            throw new ConnectException("Unable to create statement!");
Давайте назовем это исключение `DatabaseException` А то не понятно о каком именно соединении идет речь

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +            statement = dbConnection.createStatement();
statement надо открывать с помощью блока try-with-resources. 
`try(statement = dbConnection.createStatement()) {...`

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +        resultSet.close();
ResultSet  тоже надо внутри блока try-with-resources создавать

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/dao/UserProfileDAO.java
> +            System.out.println(Integer.toString(e.getErrorCode()) + ": " + e.getSQLState());
И это тоже надо сделать везде

2016-11-15 21:38 UTC, KSolovyev commented on src/main/java/ru/aviaj/service/AccountService.java
> +    protected Connection getConnection() {
Надо написать эту функцию так же как в SessionService

2016-11-15 21:38 UTC, KSolovyev commented on src/test/java/ru/aviaj/service/H2AccountService.java
> +public class H2AccountService extends AccountService {
этого сервиса в вашей ситуации не должно быть. Все можно решить с помощью одного AccountService и тестовой конфигурации на properties

2016-11-15 21:38 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=false
у вас нет jpa, убирайте. Вместо этого надо добавить боевые и тестовые настройки для jdbc

2016-11-15 21:39 UTC, KSolovyev commented
Будет еще

2016-11-15 21:44 UTC, TimeEscaper commented on src/main/java/ru/aviaj/database/dao/UserProfileDAO.java
> +            System.out.println(Integer.toString(e.getErrorCode()) + ": " + e.getSQLState());
А есть ли смысл для этого сделать отдельный сервис?

2016-11-15 21:58 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/dao/UserProfileDAO.java
> +            System.out.println(Integer.toString(e.getErrorCode()) + ": " + e.getSQLState());
Этот логгер уже подключен у вас spring-boot надо просто добавить статическое поле в каждый класс, где нужно логирование. Можете посмотреть в примерах с лекций

2016-11-15 21:58 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/dao/UserProfileDAO.java
> +            System.out.println(Integer.toString(e.getErrorCode()) + ": " + e.getSQLState());
org.slf4j.Logger

2016-11-16 20:59 UTC, KSolovyev requested changes

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +                throw new DbResultSetException(e.toString());
потеряли здесь стектрейс. Нужно строить цепочку исключений.
`throw new DbResultSetException("Unnable to execute query", e)`

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +                throw new DbResultSetException(e.toString());
И во всех местах, где вы кидаете исключение надо сделать аналогично

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/service/SessionService.java
>          return DataSourceUtils.getConnection(ds);
Прочитайте внимательно доки к методу. Этот метод является `@NotNull`, те возвращает Connection, либо кидает исключение. Проверять на null не надо

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/service/configuration/AccountServiceConfig.java
> +    public DataSource accountServiceDs() {
DataSource инжектится самим спрингом. Вам нужно только настроить соответствующий файл properties. Регистрировать bean не надо

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/service/configuration/AccountServiceConfig.java
> +    public DataSource accountServiceDs() {
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html

2016-11-16 20:59 UTC, KSolovyev commented on src/main/java/ru/aviaj/service/configuration/AccountServiceConfig.java
> +    public DataSource accountServiceDs() {
Это я к тому, что у вас одна база, в тестах своя, на проде своя. Можно сделать 2 файла application.properties, один в тестах, другой в коде

2016-11-16 21:03 UTC, TimeEscaper commented on src/main/java/ru/aviaj/service/configuration/AccountServiceConfig.java
> +    public DataSource accountServiceDs() {
Я использую in-memory базу для хранения сессий, поэтому, если я правильно понял, нужно настраивать два отдельных DataSource'а. Или тогда лучше совсем отказаться от этой идеи?

2016-11-16 22:50 UTC, TimeEscaper commented on src/main/java/ru/aviaj/service/configuration/AccountServiceConfig.java
> +    public DataSource accountServiceDs() {
Да, в итоге я отказался от этой идеи. Теперь на деплое один MySQL и один H2 в тестах.

2016-11-23 20:41 UTC, KSolovyev requested changes

2016-11-23 20:41 UTC, KSolovyev commented on src/main/java/ru/aviaj/controller/AuthenticationController.java
> +            LOGGER.error(e.getMessage() + "\nStacktrace:\n" + e.getStackTraceString());
не так. `LOGGER.error("Unnable to save session", e)` - дальше сообщения и стектрейс логгер сам выведет. А то в вашем случае, вы опять стектрейс вложенного исключения потеряете

2016-11-27 08:59 UTC, TimeEscaper commented on src/main/java/ru/aviaj/controller/AuthenticationController.java
> +            LOGGER.error(e.getMessage() + "\nStacktrace:\n" + e.getStackTraceString());
Внёс определённые изменения.

2016-12-06 21:06 UTC, KSolovyev requested changes

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/DatabaseService.java
> +public abstract class DatabaseService {
это interface

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/DatabaseService.java
> +public abstract class DatabaseService {
хотя реализация одинаковая, можно ее сюда перетащить

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/model/UserProfile.java
> +    public UserProfile(UserProfile other) {
Это что? Конструктор копирования из С++? =) 
Надо убрать

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/model/UserProfile.java
> +        this.id = 0;
здесь можно использовать ссылку на другой конструктор. Делается вот так
`this(login, email, password, 0, 0)`

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +    public <T> T execQuery(Connection dbConnection, String sqlQuery, IResultHandler<T> resultHandler)
давайте пометим аннотацией @jetbrains.annotaitions.Nullable

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +                resultSet.close();
resultSet и statement Autocloseable. Если используете try-with-resources, закрывать их не надо.

2016-12-06 21:06 UTC, KSolovyev commented on src/main/java/ru/aviaj/database/executor/Executor.java
> +            statement.close();
и здесь тоже

2016-12-06 21:06 UTC, KSolovyev commented
Правьте и будем мержить

2016-12-06 22:36 UTC, TimeEscaper commented on src/main/java/ru/aviaj/model/UserProfile.java
> +    public UserProfile(UserProfile other) {
Эта конструкция вообще не нужна в Java? Просто в некоторых примерах, что я видел, использовался подобный конструктор.

2016-12-11 16:51 UTC, KSolovyev commented
тест падает

2016-12-11 16:52 UTC, KSolovyev commented
и когда будет править иправьте все `throw new Exception()` на `Assert.assertNull` / `Assert.assertEquals`

2016-12-14 11:20 UTC, TimeEscaper commented
Поправил, за одно увеличился процент покрытия.

2016-12-14 12:12 UTC, merged