Команда AviaJ, РК №3 (Механика)
java-park-mail-ru/aviaj-09-2016 pull request #5
Opened 2016-12-23 18:05 UTC by TimeEscaper

Прототип игровой механики. Еще будут коммиты.

2016-12-23 19:22 UTC, KSolovyev commented
Хмм, а все есть, а механики, как раз, нет

2016-12-24 15:57 UTC, TimeEscaper commented
Уже немного ближе к механике, но еще не совсем механика.

2016-12-26 12:23 UTC, TimeEscaper commented
Теперь с механикой.

2016-12-28 07:24 UTC, KSolovyev requested changes

2016-12-28 07:24 UTC, KSolovyev commented on src/main/java/ru/aviaj/mechanics/Mechanics.java
> +                matchedPlayers.add(accountService.getUserById(candidateId));
ненене. Это цикл гейм механики. Здесь не должно быть обращений к базе данных

2017-01-03 18:00 UTC, TimeEscaper commented
Переделал этот момент.

2017-03-28 09:29 UTC, closed without merging